# 02_VDDC
## Variable Definition and Data Check

This notebook documents the variable definitions, missing/invalid value handling, recoding rules, and final sample size used in the analysis.

Chosen variables:
- Sleep
- SadOrHopeless

## 1. Variable Definition

### Explanatory Variable: `Sleep`
- **What it measures:** Average hours of sleep on school nights.
- **Valid codes used:** `1–7`
- Values outside this range are treated as invalid.

### Response Variable: `SadOrHopeless`
- **What it measures:** Whether the student felt sad or hopeless.
- **Valid codes used:** `1`, `2`
- **1:** Yes
- **2:** No
- Other values are treated as invalid.

In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

input_path = Path('YRBS_2007_sleep_sad_clean.csv')

## Load data

In [6]:
import pandas as pd

# 這裡我幫你把路徑修正為 OneDrive 的正確路徑了！
df = pd.read_csv(r'C:\Users\88690\OneDrive\桌面\cycle4-main\data\Processes\YRBS_2007_sleep_sad_clean.csv')

print('資料維度 Shape:', df.shape)
df[['Sleep','SadOrHopeless']].head(10)

資料維度 Shape: (12106, 2)

   Sleep  SadOrHopeless
0    5.0            1.0
1    4.0            2.0
2    1.0            1.0
3    1.0            1.0
4    6.0            2.0
5    5.0            2.0
6    5.0            2.0
7    5.0            2.0
8    5.0            2.0
9    5.0            2.0

In [9]:
import pandas as pd

# 1. 先定義好 input_path 變數（這行是關鍵！）
input_path = r'C:\Users\88690\OneDrive\桌面\cycle4-main\data\Processes\YRBS_2007_sleep_sad_clean.csv'

# 2. 接下來讀取檔案與顯示資料
df = pd.read_csv(input_path)

print("Data shape:", df.shape)
display(df.head(10))

Data shape: (12106, 2)

   Sleep  SadOrHopeless
0    5.0            1.0
1    4.0            2.0
2    1.0            1.0
3    1.0            1.0
4    6.0            2.0
5    5.0            2.0
6    5.0            2.0
7    5.0            2.0
8    5.0            2.0
9    5.0            2.0

## Step 1: Check missing / invalid values

In [10]:
sleep_col = 'Sleep'
sad_col = 'SadOrHopeless'

missing_summary = pd.DataFrame({
    'Variable':[sleep_col, sad_col],
    'Missing_Count':[
        df[sleep_col].isna().sum(),
        df[sad_col].isna().sum()
    ]
})

display(missing_summary)

        Variable  Missing_Count
0          Sleep              0
1  SadOrHopeless              0

## Step 2: Verify valid codes

In [11]:
print("Sleep values:")
print(sorted(df['Sleep'].unique()))

print("\nSadOrHopeless values:")
print(sorted(df['SadOrHopeless'].unique()))

Sleep values:
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0]

SadOrHopeless values:
[1.0, 2.0]

## Step 3: Final sample size

In [12]:
final_n = len(df)

summary = pd.DataFrame({
    'Final Sample Size':[final_n],
    'Mean Sleep':[df['Sleep'].mean()],
    'SadOrHopeless Rate (%)':[
        (df['SadOrHopeless']==1).mean()*100
    ]
})

display(summary)

   Final Sample Size  Mean Sleep  SadOrHopeless Rate (%)
0              12106     3.79663               29.580373

## Step 4: Save summary

In [13]:
summary.to_csv('sleep_sad_summary.csv', index=False)
print('Summary file saved.')

Summary file saved.

## 2. Short Summary

This notebook documents:

- Variable definitions
- Missing value checks
- Valid code verification
- Final sample size after cleaning

The cleaned dataset contains only valid observations for Sleep and SadOrHopeless and is ready for EDA and statistical analysis.